#parameters:
#    facebook.app_id:     ""
#    facebook.app_secret: ""
#    facebook.page_url:   ""
#    facebook.required_permissions: ["email"]
#    facebook.permissions_callback_route: ""


services:

# A specific facebook class declaration
#    facebook:
#        class: %facebook_service_class%
#        arguments:
#            - @session
#            - @router
#            - %facebook.app_id%
#            - %facebook.app_secret%
#            - %facebook.page_url%
#            - %facebook.required_permissions%


# A specific facebook twig extension declaration
#    twig.extension.facebook:
#        class: Becklyn\FacebookBundle\Service\FacebookTwigExtension
#        tags:
#            - { name: twig.extension }
#        arguments:
#            - '@service_container'
#            - 'facebook.service.id'
#            - false

    becklyn.facebook.utilities:
        class: Becklyn\FacebookBundle\Service\UtilitiesService

    becklyn.facebook.model.graph:
        class: Becklyn\FacebookBundle\Model\FacebookGraphModel


    twig.extension.becklyn.facebook.generic:
        class: Becklyn\FacebookBundle\Service\FacebookUtilitiesTwigExtension
        arguments: ['@becklyn.facebook.utilities']
        tags:
            - { name: twig.extension }
