#parameters:
#    facebook.app_id:     ""
#    facebook.app_secret: ""
#    facebook.page_url:   ""
#    facebook.required_permissions: ["email"]
#    facebook.permissions_callback_route: ""


services:

# A specific facebook class declaration
#    facebook:
#        class: %facebook_service_class%
#        arguments:
#            - @session
#            - %facebook.app_id%
#            - %facebook.app_secret%
#            - %facebook.page_url%
#            - %facebook.required_permissions%


# A specific facebook twig extension declaration
#    twig.extension.facebook:
#        class: OAGM\FacebookBundle\Service\FacebookTwigExtension
#        tags:
#            - { name: twig.extension }
#        arguments: [@service_container, @facebook]


    twig.extension.generic_facebook:
        class: OAGM\FacebookBundle\Service\GenericFacebookTwigExtension
        tags:
            - { name: twig.extension }



    kernel.listener.oagm_facebook:
        class: OAGM\FacebookBundle\Listener\IeIframeCookieListener
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }