#parameters:
#    facebook.app_id:     ""
#    facebook.app_secret: ""
#    facebook.page_url:   ""
#    facebook.required_permissions: ["email"]
#    facebook.permissions_callback_route: ""


services:
    becklyn.facebook.sdk:
        class: Facebook\Facebook
        public: false
        arguments:
            - app_id: '%facebook.app.id%'
              app_secret: '%facebook.app.secret%'

    becklyn.facebook.utilities:
        class: Becklyn\FacebookBundle\Service\UtilitiesService

    becklyn.facebook.model.graph:
        class: Becklyn\FacebookBundle\Model\FacebookGraphModel

    becklyn.facebook:
        class: Becklyn\FacebookBundle\Model\FacebookAppModel
        arguments:
            - '@becklyn.facebook.sdk'
            - '@session'
            - '@router'
            - '%facebook.page_url%'
            - '%facebook.required_permissions%'


    twig.extension.becklyn.facebook.generic:
        class: Becklyn\FacebookBundle\Service\FacebookUtilitiesTwigExtension
        arguments: ['@becklyn.facebook.utilities']
        tags:
            - { name: twig.extension }

    becklyn.twig.app:
        class: Becklyn\FacebookBundle\Service\FacebookAppTwigExtension
        arguments:
            - '@becklyn.facebook'
        tags:
            - { name: twig.extension }
